### PR TITLE
Feature/add arrow highlight

### PR DESCRIPTION
**Pull request by j1m-renwick**
* added attributes to enable highlighting of arrows as required - see readme for details.  
* updated snapshot tests to test for custom and default colours on a coloured background, to show that there is no unintended whitespace around the arrow.  Also fixed a couple of scenario descriptions that were wrong regarding the direction of the arrow specified in the scenario.  "npm run test" script is passing.

### CODE REVIEW

**Comment by uladkasach** [comment]
Hey there! Thank you for submitting this PR :) 

So that i can wrap my head around this - what is the use case for highlighting? I'm cautious about adding features that will be required to be maintained in the package without a strong use case.

**Comment by j1m-renwick** [comment]
Hi, thanks for looking :) My particular use case was for onHover behaviour so that could see which arrow was related to which data point at a glance (see gif below) - I guess it could also be used for visually grouping different set of arrows together - or just making UI a bit more colourful in general :D

highlight

**Comment by uladkasach** [comment]
hmm, do you think we could get a similar effect by customizing the "thickness" of the arrow and the "color" of the arrow?

For example:

```tsx
<ArrowSvg start={{ x: 0, y: 0 }} end={{ x: 500, y: 300 }} orientation={LineOrientation.HORIZONTAL} color="cyan" thickness={7} />
```

**Comment by j1m-renwick** [comment]
Hey, sorry for the delay - yes this makes sense as well, I'll have a look at updating the PR to reflect this when I get a moment :)

**Comment by j1m-renwick** [comment]
Branch has been updated, ready for review :)

**Comment by uladkasach** [comment]
this is awesome! 

two final, quick comments:
- do you mind updating the name of the `width` prop to be `strokeWidth`? It's a little more explicit that way - especially since we have a few other "width"s that we deal with in the `ArrowSvg` component 
- do you mind exposing the `strokeWidth` and `color` property with the defaults through the `ArrowBetweenDivs` component too? It will just need to forward those two props to the `ArrowSvg` that it instantiates

thank you for this definitely needed feature and the test fixes! very much appreciated

**Comment by uladkasach** [comment]
you're amazing - thank you very much for making this happen!

**Pull request merged**
